# Node.js React Web App to Linux on Azure
# Build a Node.js React app and deploy it to Azure as a Linux web app.
# Docs: https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

variables:
  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: '8bbd7f8f-ea6d-412b-b5f1-3f30eab55f4a'

  # Web app name
  webAppName: 'uncyber'

  # Environment name
  environmentName: 'uncyber'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

  # Define the working directory to the project folder
  workingDirectory: '$(System.DefaultWorkingDirectory)/web-asp-net/UN.CYBERCOM.Web/un.cybercom.web.client'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        # Archive files from the proper working directory
        rootFolderOrFile: '$(workingDirectory)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        replaceExistingArchive: true

    - upload: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      artifact: drop

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: Deploy
    displayName: Deploy
    environment: $(environmentName)
    pool:
      vmImage: $(vmImageName)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureRmWebAppDeployment@4
            displayName: 'Azure App Service Deploy: uncyber'
            inputs:
              azureSubscription: $(azureSubscription)
              appType: webAppLinux
              WebAppName: $(webAppName)
              packageForLinux: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
              RuntimeStack: 'NODE|20LTS'
              StartupCommand: 'npm run start'
              ScriptType: 'Inline Script'
              InlineScript: |
                cd web-asp-net/UN.CYBERCOM.Web/un.cybercom.web.client
                npm install
                npm run build --if-present
