/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace MembershipManagement {
  export type VotingParametersStruct = {
    randomizeByGroup: boolean;
    randomizeByMember: boolean;
    outputCountForGroup: BigNumberish;
    outputCountForMember: BigNumberish;
    voteDenominator: BigNumberish;
    voteNumerator: BigNumberish;
    sumDenominator: BigNumberish;
    sumNumerator: BigNumberish;
    avgVotes: boolean;
  };

  export type VotingParametersStructOutput = [
    randomizeByGroup: boolean,
    randomizeByMember: boolean,
    outputCountForGroup: bigint,
    outputCountForMember: bigint,
    voteDenominator: bigint,
    voteNumerator: bigint,
    sumDenominator: bigint,
    sumNumerator: bigint,
    avgVotes: boolean
  ] & {
    randomizeByGroup: boolean;
    randomizeByMember: boolean;
    outputCountForGroup: bigint;
    outputCountForMember: bigint;
    voteDenominator: bigint;
    voteNumerator: bigint;
    sumDenominator: bigint;
    sumNumerator: bigint;
    avgVotes: boolean;
  };

  export type ChangeVotingParametersRoleStruct = {
    council: BytesLike;
    parameters: MembershipManagement.VotingParametersStruct;
  };

  export type ChangeVotingParametersRoleStructOutput = [
    council: string,
    parameters: MembershipManagement.VotingParametersStructOutput
  ] & {
    council: string;
    parameters: MembershipManagement.VotingParametersStructOutput;
  };

  export type VoteStruct = {
    member: AddressLike;
    voteCasted: boolean;
    timestamp: BigNumberish;
    proposalId: BigNumberish;
  };

  export type VoteStructOutput = [
    member: string,
    voteCasted: boolean,
    timestamp: bigint,
    proposalId: bigint
  ] & {
    member: string;
    voteCasted: boolean;
    timestamp: bigint;
    proposalId: bigint;
  };

  export type ChangeVotingParametersResponseStruct = {
    id: BigNumberish;
    parameters: MembershipManagement.ChangeVotingParametersRoleStruct[];
    votes: MembershipManagement.VoteStruct[];
    duration: BigNumberish;
    status: BigNumberish;
    isProcessing: boolean;
    votingStarted: boolean;
    owner: AddressLike;
    proposalAddress: AddressLike;
    packageAddress: AddressLike;
  };

  export type ChangeVotingParametersResponseStructOutput = [
    id: bigint,
    parameters: MembershipManagement.ChangeVotingParametersRoleStructOutput[],
    votes: MembershipManagement.VoteStructOutput[],
    duration: bigint,
    status: bigint,
    isProcessing: boolean,
    votingStarted: boolean,
    owner: string,
    proposalAddress: string,
    packageAddress: string
  ] & {
    id: bigint;
    parameters: MembershipManagement.ChangeVotingParametersRoleStructOutput[];
    votes: MembershipManagement.VoteStructOutput[];
    duration: bigint;
    status: bigint;
    isProcessing: boolean;
    votingStarted: boolean;
    owner: string;
    proposalAddress: string;
    packageAddress: string;
  };

  export type ChangeVotingParametersRequestStruct = {
    parameters: MembershipManagement.ChangeVotingParametersRoleStruct[];
    duration: BigNumberish;
    owner: AddressLike;
  };

  export type ChangeVotingParametersRequestStructOutput = [
    parameters: MembershipManagement.ChangeVotingParametersRoleStructOutput[],
    duration: bigint,
    owner: string
  ] & {
    parameters: MembershipManagement.ChangeVotingParametersRoleStructOutput[];
    duration: bigint;
    owner: string;
  };
}

export interface VotingParametersManagerInterface extends Interface {
  getFunction(
    nameOrSignature: "getRequests" | "submitProposal"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "ProposalCreated"): EventFragment;

  encodeFunctionData(
    functionFragment: "getRequests",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitProposal",
    values: [MembershipManagement.ChangeVotingParametersRequestStruct]
  ): string;

  decodeFunctionResult(
    functionFragment: "getRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitProposal",
    data: BytesLike
  ): Result;
}

export namespace ProposalCreatedEvent {
  export type InputTuple = [
    proposalId: BigNumberish,
    proposalAddress: AddressLike
  ];
  export type OutputTuple = [proposalId: bigint, proposalAddress: string];
  export interface OutputObject {
    proposalId: bigint;
    proposalAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface VotingParametersManager extends BaseContract {
  connect(runner?: ContractRunner | null): VotingParametersManager;
  waitForDeployment(): Promise<this>;

  interface: VotingParametersManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getRequests: TypedContractMethod<
    [status: BigNumberish],
    [MembershipManagement.ChangeVotingParametersResponseStructOutput[]],
    "view"
  >;

  submitProposal: TypedContractMethod<
    [request: MembershipManagement.ChangeVotingParametersRequestStruct],
    [string],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getRequests"
  ): TypedContractMethod<
    [status: BigNumberish],
    [MembershipManagement.ChangeVotingParametersResponseStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "submitProposal"
  ): TypedContractMethod<
    [request: MembershipManagement.ChangeVotingParametersRequestStruct],
    [string],
    "nonpayable"
  >;

  getEvent(
    key: "ProposalCreated"
  ): TypedContractEvent<
    ProposalCreatedEvent.InputTuple,
    ProposalCreatedEvent.OutputTuple,
    ProposalCreatedEvent.OutputObject
  >;

  filters: {
    "ProposalCreated(uint256,address)": TypedContractEvent<
      ProposalCreatedEvent.InputTuple,
      ProposalCreatedEvent.OutputTuple,
      ProposalCreatedEvent.OutputObject
    >;
    ProposalCreated: TypedContractEvent<
      ProposalCreatedEvent.InputTuple,
      ProposalCreatedEvent.OutputTuple,
      ProposalCreatedEvent.OutputObject
    >;
  };
}
