/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ChangeVotingParametersProposal__factory } from "./ChangeVotingParametersProposal__factory";
export { MembershipProposal__factory } from "./MembershipProposal__factory";
export { MembershipRemovalProposal__factory } from "./MembershipRemovalProposal__factory";
export { Proposal__factory } from "./Proposal__factory";
export { ProposalStorageManager__factory } from "./ProposalStorageManager__factory";
