/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace MembershipManagement {
  export type NationStruct = { id: AddressLike; name: string };

  export type NationStructOutput = [id: string, name: string] & {
    id: string;
    name: string;
  };

  export type VoteStruct = {
    member: AddressLike;
    voteCasted: boolean;
    timestamp: BigNumberish;
    proposalId: BigNumberish;
  };

  export type VoteStructOutput = [
    member: string,
    voteCasted: boolean,
    timestamp: bigint,
    proposalId: bigint
  ] & {
    member: string;
    voteCasted: boolean;
    timestamp: bigint;
    proposalId: bigint;
  };

  export type MembershipRemovalResponseStruct = {
    id: BigNumberish;
    nationToRemove: MembershipManagement.NationStruct;
    votes: MembershipManagement.VoteStruct[];
    duration: BigNumberish;
    status: BigNumberish;
    isProcessing: boolean;
    votingStarted: boolean;
    owner: AddressLike;
    proposalAddress: AddressLike;
  };

  export type MembershipRemovalResponseStructOutput = [
    id: bigint,
    nationToRemove: MembershipManagement.NationStructOutput,
    votes: MembershipManagement.VoteStructOutput[],
    duration: bigint,
    status: bigint,
    isProcessing: boolean,
    votingStarted: boolean,
    owner: string,
    proposalAddress: string
  ] & {
    id: bigint;
    nationToRemove: MembershipManagement.NationStructOutput;
    votes: MembershipManagement.VoteStructOutput[];
    duration: bigint;
    status: bigint;
    isProcessing: boolean;
    votingStarted: boolean;
    owner: string;
    proposalAddress: string;
  };

  export type MembershipRemovalRequestStruct = {
    nationToRemove: AddressLike;
    duration: BigNumberish;
    owner: AddressLike;
  };

  export type MembershipRemovalRequestStructOutput = [
    nationToRemove: string,
    duration: bigint,
    owner: string
  ] & { nationToRemove: string; duration: bigint; owner: string };
}

export interface MembershipRemovalManagerInterface extends Interface {
  getFunction(
    nameOrSignature: "getMembershipRemovalRequests" | "submitProposal"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "ProposalCreated"): EventFragment;

  encodeFunctionData(
    functionFragment: "getMembershipRemovalRequests",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitProposal",
    values: [MembershipManagement.MembershipRemovalRequestStruct]
  ): string;

  decodeFunctionResult(
    functionFragment: "getMembershipRemovalRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitProposal",
    data: BytesLike
  ): Result;
}

export namespace ProposalCreatedEvent {
  export type InputTuple = [
    proposalId: BigNumberish,
    proposalAddress: AddressLike
  ];
  export type OutputTuple = [proposalId: bigint, proposalAddress: string];
  export interface OutputObject {
    proposalId: bigint;
    proposalAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MembershipRemovalManager extends BaseContract {
  connect(runner?: ContractRunner | null): MembershipRemovalManager;
  waitForDeployment(): Promise<this>;

  interface: MembershipRemovalManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getMembershipRemovalRequests: TypedContractMethod<
    [status: BigNumberish],
    [MembershipManagement.MembershipRemovalResponseStructOutput[]],
    "view"
  >;

  submitProposal: TypedContractMethod<
    [request: MembershipManagement.MembershipRemovalRequestStruct],
    [string],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getMembershipRemovalRequests"
  ): TypedContractMethod<
    [status: BigNumberish],
    [MembershipManagement.MembershipRemovalResponseStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "submitProposal"
  ): TypedContractMethod<
    [request: MembershipManagement.MembershipRemovalRequestStruct],
    [string],
    "nonpayable"
  >;

  getEvent(
    key: "ProposalCreated"
  ): TypedContractEvent<
    ProposalCreatedEvent.InputTuple,
    ProposalCreatedEvent.OutputTuple,
    ProposalCreatedEvent.OutputObject
  >;

  filters: {
    "ProposalCreated(uint256,address)": TypedContractEvent<
      ProposalCreatedEvent.InputTuple,
      ProposalCreatedEvent.OutputTuple,
      ProposalCreatedEvent.OutputObject
    >;
    ProposalCreated: TypedContractEvent<
      ProposalCreatedEvent.InputTuple,
      ProposalCreatedEvent.OutputTuple,
      ProposalCreatedEvent.OutputObject
    >;
  };
}
