/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface DocumentInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "dochash"
      | "owningContract"
      | "signature"
      | "signer"
      | "timestamp"
      | "title"
      | "url"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "dochash", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "owningContract",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "signature", values?: undefined): string;
  encodeFunctionData(functionFragment: "signer", values?: undefined): string;
  encodeFunctionData(functionFragment: "timestamp", values?: undefined): string;
  encodeFunctionData(functionFragment: "title", values?: undefined): string;
  encodeFunctionData(functionFragment: "url", values?: undefined): string;

  decodeFunctionResult(functionFragment: "dochash", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "owningContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "signature", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "signer", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "timestamp", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "title", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "url", data: BytesLike): Result;
}

export interface Document extends BaseContract {
  connect(runner?: ContractRunner | null): Document;
  waitForDeployment(): Promise<this>;

  interface: DocumentInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  dochash: TypedContractMethod<[], [string], "view">;

  owningContract: TypedContractMethod<[], [string], "view">;

  signature: TypedContractMethod<[], [string], "view">;

  timestamp: TypedContractMethod<[], [bigint], "view">;

  title: TypedContractMethod<[], [string], "view">;

  url: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "dochash"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owningContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "signature"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "signer"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "timestamp"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "title"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "url"
  ): TypedContractMethod<[], [string], "view">;

  filters: {};
}
